Window ByPass
jmcollin78/versatile_thermostat pull request #143
Opened 2023-10-28 19:37 UTC by adi90x

Hello,

Comme discuté, une PR pour ajouter une fonction de bypass de l'ouverture/fermeture de la fenetre.
Dans le cas ou le bypass est désactivé alors que le dernier état de la fenetre est ouvert je bascule en HVAC_OFF.
C'est la deuxieme PR car je n'avais pas pris les enormes modifs :+1:  => cette PR est mergeable tel quel ! 

Je regarde l'autre point ( interdire le passage en HVAC_HEAT si la fenetre est ouverte demain )

Bonne soirée,
Adrien

2023-10-28 21:29 UTC, jmcollin78 commented
Déjà !? Wahou, tu m'impressionnes

Est-ce tu peux ajouter un test unitaire stp pour prouver que ca marche ?

Pour lancer les tests unitaires, tu vas dans VSCode, en mode container, tu cliques sur  
![Capture d’écran 2023-10-28 à 23 27 57](https://github.com/jmcollin78/versatile_thermostat/assets/1712374/312dff5f-3be3-4686-a47f-650e6ddcea8f)
 puis sur 
![Capture d’écran 2023-10-28 à 23 28 15](https://github.com/jmcollin78/versatile_thermostat/assets/1712374/9ae2882c-9558-4e4f-926c-001f9b4b66f5)

Tout doit être au vert.

Tu peux t'inspirer de ce qui est fait dans le test test/test_window.py pour ajouter au moins un test.

Je fais une relecture quand même en attendant.

2023-10-28 21:50 UTC, jmcollin78 requested changes
Super job !
J'ai pas grand chose à dire.

2023-10-28 21:50 UTC, jmcollin78 commented on README-fr.md
> +Il permet de continuer à chauffer même si la fenetre est detecté ouverte.
détectée

2023-10-28 21:50 UTC, jmcollin78 commented on README-fr.md
> +Pour changer le paramétre de bypass utilisez le code suivant :
paramètre

2023-10-28 21:50 UTC, jmcollin78 commented on README-fr.md
>  service : thermostat_polyvalent.set_security
versatile_thermostat (à faire partout, je sens que le traducteur a fait du zele).

2023-10-28 21:50 UTC, jmcollin78 commented on README.md
>  service : thermostat_polyvalent.set_security
versatile_thermostat (à faire partout)

2023-10-28 21:50 UTC, jmcollin78 commented on custom_components/versatile_thermostat/base_thermostat.py
> +                self.update_custom_attributes()
Normalement rien n'a changé (puisqu'on ignore l'évent), donc pas la peine d'appeler self.update_custom_attributes.

2023-10-28 21:50 UTC, jmcollin78 commented on custom_components/versatile_thermostat/base_thermostat.py
> +        self._window_bypass_state = window_bypass
Ajouter un test pour vérifier qu'il y a un réellement un changement de valeur de window_bypass_state et ne rien faire dans ce cas.

2023-10-28 21:50 UTC, jmcollin78 commented on custom_components/versatile_thermostat/base_thermostat.py
> +        self.update_custom_attributes()
Déjà appelé par async_set_hvac_mode et par restore_hvac_mode donc je pense que ca ne sert à rien.

2023-10-28 21:50 UTC, jmcollin78 commented on custom_components/versatile_thermostat/binary_sensor.py
> +            return "mdi:check-circle-outline"
Je préfère mdi:window-shutter-alert (ou window-shutter-cog)

Les icones sont là pour info: https://pictogrammers.com/library/mdi/

2023-10-28 21:50 UTC, jmcollin78 commented on custom_components/versatile_thermostat/binary_sensor.py
> +            return "mdi:alpha-b-circle-outline"
Je préfère mdi:window-shutter-auto

2023-10-28 21:57 UTC, adi90x commented on README-fr.md
> +Il permet de continuer à chauffer même si la fenetre est detecté ouverte.
Corrigé

2023-10-28 21:57 UTC, adi90x commented on README-fr.md
> +Pour changer le paramétre de bypass utilisez le code suivant :
Corrigé

2023-10-28 21:57 UTC, adi90x commented on README-fr.md
>  service : thermostat_polyvalent.set_security
Corrigé

2023-10-28 21:58 UTC, adi90x commented on README.md
>  service : thermostat_polyvalent.set_security
Corrigé

2023-10-29 06:20 UTC, jmcollin78 commented on custom_components/versatile_thermostat/base_thermostat.py
> +                _LOGGER.debug("Window ByPass is activated. Ignore window event")
_LOGGER.info

2023-10-29 22:55 UTC, adi90x commented
Bonsoir, 
J'ai ajouté un test de bon fonctionnement du bypass ( i.e : le thermostat reste en HEAT malgré que la fenetre soit ouverte )
Une premiere donc il n'est surement pas parfait :)
Bonne soirée !

2023-10-29 23:04 UTC, jmcollin78 commented on tests/test_window.py
> +        #assert mock_send_event.call_count == 1
assert mock_send_event.call_count == 0

2023-10-29 23:07 UTC, jmcollin78 commented on tests/test_window.py
> +        #assert mock_send_event.call_count == 1
ok

2023-10-29 23:08 UTC, jmcollin78 commented
Plus que 3 petits commentaires et on est bon.

2023-10-29 23:23 UTC, adi90x commented
> Plus que 3 petits commentaires et on est bon.

Il manque quoi  ?

2023-10-30 06:40 UTC, jmcollin78 commented
> Il manque quoi ?

Ben il reste 3 commentaires. Tu ne les vois pas ?

1. "Normalement rien n'a changé (puisqu'on ignore l'évent), donc pas la peine d'appeler self.update_custom_attributes."
2. "Ajouter un test pour vérifier qu'il y a un réellement un changement de valeur de window_bypass_state et ne rien faire dans ce cas."
3. "Déjà appelé par async_set_hvac_mode et par restore_hvac_mode donc je pense que ca ne sert à rien."

2023-10-30 06:47 UTC, merged

2023-10-30 06:48 UTC, jmcollin78 commented
Merged ! Thank you @adi90x !

2023-10-30 07:11 UTC, adi90x commented
> Merged ! Thank you @adi90x !

Yes les commentaires était gérés ! Merci pour tes commentaires et ta réactivité ! Je regarde dans la semaine pour empêcher le switch vers HEAT si la fenêtre est ouverte !

Bonne journée et bonne semaine !

2023-10-30 07:17 UTC, jmcollin78 commented
While testing I see:
`VersatileThermostat-Thermostat switch 1 - Window ByPass is activated. Ignore window event`
and
![Capture d’écran 2023-10-30 à 08 04 15](https://github.com/jmcollin78/versatile_thermostat/assets/1712374/53384d46-cfe7-44d9-9376-cf981495256c)

Quand j'enlève le bypass ca revient bien actif. Donc ça marche pour le cas nominal. 

--- 
Y a un cas qui ne marche pas:
1. y a un mode de détection des ouvertures qui est fait lorsque la température chute. C'est le mode window auto.
2. dans ce mode, le bypass ne fonctionne pas.

Je vais regarder si c'est simple à corriger.

2023-10-30 08:24 UTC, jmcollin78 commented
C'est corrigé. J'en ai profité pour ajouter des tests et un thème pour changer la couleur du binary_sensor Window bypass.
Toutes les modifs sont là si tu veux jeter un oeil: https://github.com/jmcollin78/versatile_thermostat/commit/dc89e011c796d057743b157b956b7a6d02673dc4

Je release dans la foulée.

2023-10-30 09:04 UTC, adi90x commented
J'ai juste ajouté un petit commentaire, avec le dernier commit, tu supprime l'enregistrement de l'état de la fenêtre lorsque le bypass est activé, alors que l'on souhaite garder en mémoire le ```_window.state```

2023-10-30 09:15 UTC, jmcollin78 commented
Vu !

https://github.com/jmcollin78/versatile_thermostat/commit/923d374ce3bb531a869f10a03a1c80b9efb29932